version: 2

build:
  os: ubuntu-22.04 
  tools:
    python:
      version: "3.10"
  jobs:
    pre_install:
      - pip install --upgrade pip
  python:
    install:
      - requirements: requirements.txt